### ISSUE TITLE
Feature Request: WAF Icon not displaying

### ISSUE THREAD

**Issue by bestickley** [pistazie/cdk-dia#41]
Hi, this tool is amazing! Thank you so much! I'd like to request icons for WAF constructs. I'd be happy to contribute if someone can point me in the right direction.

**Comment by pistazie** [comment]
Thanks @bestickley.

The matching is here: https://github.com/pistazie/cdk-dia/blob/0de795fb130b511dbe12e28928e52454bd281349/src/diagram/aws/awsResouceIconMatches.json#L1920

presumably, you are using WAFV2 which unlike WAF has no icons. Happy if you can add these (I guess just copy the icons that are link for WAF)
