### ISSUE TITLE
Resource Support

### ISSUE THREAD

**Issue by cjhelloletsgo** [pistazie/cdk-dia#47]
Hey, thanks for the really cool project! I want to use it more but at my company we use a lot of Amazon Lex and Connect resources which both seem to not have any icons currently. Any chance of supporting those?

**Comment by pistazie** [comment]
thanks, @cjhelloletsgo 
I added the icons in #48

**Comment by cjhelloletsgo** [comment]
Wow, thank you for the extremely speedy response!
