### ISSUE TITLE
Merge with cfn-diagram?

### ISSUE THREAD

**Issue by sholtomaud** [pistazie/cdk-dia#8]
Wondering whether these two projects could come together. 

cfn-diagram is nice because it exports draw.io (which is available in VSCode Extensions)
cdk-dia is nice because it is "DaC". 

[cfn-diagram](https://github.com/mhlabs/cfn-diagram)

**Comment by pistazie** [comment]
Hi Sholto,

I guess a merge won't make too much sense as CDK-DIA is based in the CDK tree and cfn-diagram deals with Cfn templates.

Most of CDK-DIA's magic is in the `diagram` module and I guess one could write rather easily an additional draw.io renderer.

In one of my latest commits to a [branch](https://github.com/pistazie/cdk-dia/commits/multiple_renderers) I extracted a `DiagramRenderer` interface one could implement for such a use case (that was implemented as another contributor wants to try and implement a more interactive diagram). 

If you any one wants to pitch in and write such a renderer please don't hesitate to reach out to me for an intro.

**Comment by sholtomaud** [comment]
Hi @pistazie,

Thank you for the response. I understand. 

Interactive diagrams would be a very interesting use case. The entire list of tools at [https://aws.amazon.com/architecture/icons/](https://aws.amazon.com/architecture/icons/ ) would be hard to support.

**Comment by pistazie** [comment]
@sholtomaud interactive diagrams add in https://github.com/pistazie/cdk-dia/tree/0.5.0 as beta for now
